<a href="https://colab.research.google.com/github/nhlong1512/IS403.N21/blob/main/Lab3_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd 
import numpy as np
home_value = pd.read_csv("home_value.csv", sep=";")
home_value

    House Age  Square Feet  Market Value
0          33        1.812         90000
1          32        1.914        104400
2          32        1.842         93300
3          33        1.812         91000
4          32        1.836        101900
5          33        2.028        108500
6          32        1.732         87600
7          33        1.850         96000
8          32        1.791         89200
9          33        1.666         88400
10         32        1.852        100800
11         32        1.620         96700
12         32        1.692         87500
13         32        2.372        114000
14         32        2.372        113200
15         33        1.666         87500
16         32        2.123        116100
17         32        1.620         94700
18         32        1.731         86400
19         32        1.666         87100
20         28        1.520         83400
21         27        1.484         79800
22         28        1.588         81500
23         28        1.598         87100
24         28        1.484         82600
25         28        1.484         78800
26         28        1.520         87600
27         27        1.701         94200
28         28        1.484         82000
29         28        1.468         88100
30         28        1.520         88100
31         27        1.520         88600
32         27        1.484         76600
33         28        1.520         84400
34         27        1.668         90900
35         28        1.588         81000
36         28        1.784         91300
37         27        1.484         81300
38         27        1.520        100700
39         28        1.520         87200
40         27        1.684         96700
41         27        1.581        120700

In [12]:
x, y = np.array(home_value[["Square Feet", "House Age"]]).reshape((-1,2)), np.array(home_value["Market Value"]).reshape((-1,1))

In [14]:
%pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sklearn
  Building wheel for sklearn (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2955 sha256=3c8f25bde442beae1e7690becb5cc056238497a9cd52d6888ab7721419ffc90a
  Stored in directory: /root/.cache/pip/wheels/f8/e0/3d/9d0c2020c44a519b9f02ab4fa6d2a4a996c98d79ab2f569fa1
Successfully built sklearn
Installing collected packages: sklearn
Successfully installed sklearn-0.0.post1

In [16]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [17]:
print("Hệ số chẵn: ", model.intercept_)
print("Hệ số phụ thuộc: ", model.coef_)
print("Điểm R Square: ", model.score(x, y))

Hệ số chẵn:  [47331.38153562]
Hệ số phụ thuộc:  [[40911.06844844  -825.16122035]]
Điểm R Square:  0.5557624615954795